### PR TITLE
Always keep number of shards between min/max interval

### PR DESCRIPTION
**Pull request by CesarManriqueH**
**Context:**

I want to prevent situations when the autoscaling won't work because the number of shards is less than `minShards` or greater than `maxShards`.

For example:

If we have a stream with 1 shard and a scaling config with `minShards=5`, the autoscaling won't kick in because the current number or shards is less than `minShards`. The kinesis stream will stay forever at 1 shard and we will get a lot of read/write throughput exceeded errors.

This will also happen when updating the scaling configuration if the current number shards is out of limits.

**Description of changes:**

The reason of the behavior described above are these two lines:

https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/6602ab03d93e2a57a7cb06393820b5d070fb0dec/src/main/java/com/amazonaws/services/kinesis/scaling/StreamScaler.java#L450

https://github.com/awslabs/amazon-kinesis-scaling-utils/blob/6602ab03d93e2a57a7cb06393820b5d070fb0dec/src/main/java/com/amazonaws/services/kinesis/scaling/StreamScaler.java#L452

There we are not considering the scale direction which is important to make the number of shards drift into the desired interval (minShards to maxShards) when necessary.

[This commit](https://github.com/awslabs/amazon-kinesis-scaling-utils/commit/7290aa3fe358c02f693b46a869bc1ae3719269be) contains the main change. The rest are just a couple of refactorings.

### CODE REVIEW

**Comment by IanMeyers** [comment]
So the condition this doesn't catch would be as follows, and I wonder if your principle is more the right one. Say we have an idle stream with a configuration that indicates a minShards of 3. We will scale down to 3 shards, and then stop scaling down as we are at the minShards limit. We then update the configuration to state minShards of 5. Because we have an idle stream, this logic will continue to try to scale down, and the minShards will stay at 3. However, by your logic, the minShards should actually increase to 5. I can see both for and against arguments about it working either way. However, the operating principle that minShards/maxShards should dictate the range the Stream should be in is relatively unambiguous, and in the above example I think we should scale up. Therefore, I would propose that instead of making this change, when we trap the condition of target < min, or target > max, we simply set target = min/max and then let the scaling happen.

Thoughts?

**Comment by CesarManriqueH** [comment]
I totally missed the case that you described. I like the solution you proposed because it better enforces that the number shards stays between min/max and accounts for your case as well as the two cases I explained above.

**Comment by CesarManriqueH** [comment]
Btw I've read some comments about unit tests but I can't find any test files. Are there any?

**Comment by IanMeyers** [comment]
Looks very close to perfect. Can you just bump the version number in StreamScaler and pom.xml as this will be used to generate the build?

**Comment by IanMeyers** [comment]
> Btw I've read some comments about unit tests but I can't find any test files. Are there any?

There are, but not in the public repo. Will look to move them in.

**Pull request merged**
